language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t rodrigop/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rodrigop/docker-react npm rum test