language: generic
services:
  - docker

before_install:
  - docker build -t rodrigop/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rodrigop/docker-react npm rum test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-124364459481"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY